// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:465484161066:ios:a9f21d9c3ae47abfb3a353',
    messagingSenderId: '465484161066',
    projectId: 'mps2pr8',
    storageBucket: 'mps2pr8.firebasestorage.app',
    iosBundleId: 'com.example.mps2pr8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmENJvCZMrKR9TovB9ws7_yx84Vf9Af5U',
    appId: '1:465484161066:ios:a9f21d9c3ae47abfb3a353',
    messagingSenderId: '465484161066',
    projectId: 'mps2pr8',
    storageBucket: 'mps2pr8.firebasestorage.app',
    iosBundleId: 'com.example.mps2pr8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWqYebvAvvPzTIWQIcNcXXxCO5u2aHW3A',
    appId: '1:465484161066:web:f0735f1b1fa1d566b3a353',
    messagingSenderId: '465484161066',
    projectId: 'mps2pr8',
    authDomain: 'mps2pr8.firebaseapp.com',
    storageBucket: 'mps2pr8.firebasestorage.app',
    measurementId: 'G-QT80674EH3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWqYebvAvvPzTIWQIcNcXXxCO5u2aHW3A',
    appId: '1:465484161066:web:f0735f1b1fa1d566b3a353',
    messagingSenderId: '465484161066',
    projectId: 'mps2pr8',
    authDomain: 'mps2pr8.firebaseapp.com',
    storageBucket: 'mps2pr8.firebasestorage.app',
    measurementId: 'G-QT80674EH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFR1W1yDZshGkjNmFLuEDZy1brH12xIFY',
    appId: '1:465484161066:android:055945df5ee63d48b3a353',
    messagingSenderId: '465484161066',
    projectId: 'mps2pr8',
    storageBucket: 'mps2pr8.firebasestorage.app',
  );

}